ALTER TABLE votes ADD COLUMN ip TEXT NOT NULL DEFAULT '';
ALTER TABLE votes ADD COLUMN user_agent TEXT NOT NULL DEFAULT '';
ALTER TABLE votes ADD COLUMN country TEXT NOT NULL DEFAULT '';
ALTER TABLE votes ADD COLUMN as_organization TEXT NOT NULL DEFAULT '';
ALTER TABLE votes ADD COLUMN asn INTEGER;
ALTER TABLE votes ADD COLUMN is_suspicious INTEGER NOT NULL DEFAULT 0;
ALTER TABLE votes ADD COLUMN suspicious_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE votes ADD COLUMN threat_score INTEGER;
ALTER TABLE votes ADD COLUMN created_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE votes ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS votes_ip_index ON votes (ip);
CREATE INDEX IF NOT EXISTS votes_is_suspicious_index ON votes (is_suspicious);
CREATE INDEX IF NOT EXISTS votes_updated_at_index ON votes (updated_at);
